version: "3"

services:
  backend:
    build:
      context: ./
      dockerfile: ./nest-api/Dockerfile
    container_name: nest-api
    ports:
      - 3000:3000

  frontend:
    build:
      context: ./
      dockerfile: ./react-app/Dockerfile
    container_name: react-app
    ports:
      - 3001:3000
    depends_on:
      - backend
